services:
  - type: web
    name: saravanastores-billing
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
