services:
  - type: web
    name: saravanastores-billing
    env: node
    plan: free
    rootDirectory: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
